[package]
name = "coeus"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
edition = "2018"

[dependencies]
coeus-common       = { path = "../common" }
futures-io-preview = "0.3.0-alpha.16"
