[package]
name    = "stored"
version = "0.2.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
heph              = { version = "0.4.0",   default-features = false }
itoa              = { version = "1.0.4",   default-features = false }
log               = { version = "0.4.17",  default-features = false, features = ["kv_unstable_std", "release_max_level_info"] }
ring              = { version = "0.16.20", default-features = false, features = ["std"] }
serde             = { version = "1.0.145", default-features = false, features = ["derive"] }
toml              = { version = "0.5.9",   default-features = false }

# TODO: use released version.
hashmap = { version = "0.1.0", default-features = false, git = "https://github.com/Thomasdezeeuw/left-right", rev = "132427c88e203f35126716f5b17b927f48eb371b" }

[dev-dependencies]
http        = { version = "0.2.1", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
mio         = { version = "0.8.0", default-features = false, features = ["os-poll"] }
mio-pipe    = { version = "0.1.1", default-features = false }
serde_test  = { version = "1.0.116", default-features = false }

[profile.release]
opt-level        = 3
debug            = false
debug-assertions = false
overflow-checks  = false
lto              = "fat"
panic            = "unwind"
incremental      = false
codegen-units    = 1
rpath            = false

[workspace]
members = ["bench/hashmap_hash"]
