[package]
name = "stored"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
chrono     = { version = "0.4.11", default-features = false, features = ["clock"] }
evmap      = { version = "6.0.0", default-features = false }
futures-io = { version = "0.3.4", default-features = false, features = ["std"] }
futures-util = { version = "0.3.4", default-features = false, features = ["io", "std"] }
# TODO: replace with published crate.
heph       = { path = "../heph" }
log        = { version = "0.4.6", default-features = false }
ring       = { version = "0.16.2", default-features = false }
libc       = { version = "0.2.67", default-features = false }
# Need the `std` feature as it implements `Error` for `httparse::Error`.
httparse   = { version = "1.3.4", default-features = false, features = ["std"] }

[[bin]]
name = "store"
path = "src/bin/store.rs"

[[bin]]
name = "retrieve"
path = "src/bin/retrieve.rs"

[[bin]]
name = "remove"
path = "src/bin/remove.rs"

[[bin]]
name = "stored"
path = "src/bin/server.rs"
