[package]
name = "stored"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
chrono     = { version = "0.4.11", default-features = false, features = ["clock"] }
crossbeam-channel = { version = "0.4.0", default-features = false }
futures-io = { version = "0.3.4", default-features = false, features = ["std"] }
futures-util = { version = "0.3.5", default-features = false, features = ["io", "std", "write-all-vectored"] }
# TODO: replace with published crate.
heph       = { path = "../heph" }
libc       = { version = "0.2.67", default-features = false }
log        = { version = "0.4.6", default-features = false }
num_cpus   = { version = "1.12.0", default-features = false }
ring       = { version = "0.16.2", default-features = false }
# Need the `std` feature as it implements `Error` for `httparse::Error`.
httparse   = { version = "1.3.4", default-features = false, features = ["std"] }
human-size = { version = "0.4.1", default-features = false, features = ["enable-serde"] }
serde      = { version = "1.0.105", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.52", default-features = false, features = ["std"] }
toml       = { version = "0.5.6", default-features = false }

[dev-dependencies]
http        = { version = "0.2.0", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
mio         = { version = "0.7.0", default-features = false, features = ["os-poll"] }
mio-pipe    = { version = "0.1.1", default-features = false }
serde_test  = { version = "1.0.110", default-features = false }

[[bin]]
name = "store"
path = "src/bin/store.rs"

[[bin]]
name = "retrieve"
path = "src/bin/retrieve.rs"

[[bin]]
name = "remove"
path = "src/bin/remove.rs"

[[bin]]
name = "stored"
path = "src/bin/server.rs"

[[bin]]
name = "validate_store"
path = "src/bin/validate.rs"

[workspace]
members = ["bench/hashmap_hash"]
