[package]
name    = "stored"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
chrono            = { version = "0.4.11", default-features = false, features = ["clock"] }
crossbeam-channel = { version = "0.4.0", default-features = false }
futures-io        = { version = "0.3.4", default-features = false, features = ["std"] }
futures-util      = { version = "0.3.5", default-features = false, features = ["io", "std", "write-all-vectored"] }
fxhash            = { version = "0.2.1", default-features = false }
# TODO: replace with published crate.
heph              = { path = "../heph" }
libc              = { version = "0.2.67", default-features = false }
log               = { version = "0.4.6", default-features = false, features = ["release_max_level_info"] }
num_cpus          = { version = "1.12.0", default-features = false }
ring              = { version = "0.16.2", default-features = false }
# Need the `std` feature as it implements `Error` for `httparse::Error`.
httparse          = { version = "1.3.4", default-features = false, features = ["std"] }
human-size        = { version = "0.4.1", default-features = false, features = ["enable-serde"] }
parking_lot       = { version = "0.10.0", default-features = false, features = ["nightly"] }
serde             = { version = "1.0.105", default-features = false, features = ["derive"] }
serde_json        = { version = "1.0.52", default-features = false, features = ["std"] }
toml              = { version = "0.5.6", default-features = false }

# FIXME: use properly released version. Depends on https://github.com/rust-lang/futures-rs/pull/2187.
[patch.crates-io]
futures-core = { git = "https://github.com/Thomasdezeeuw/futures-rs", branch = "write-all-vectored" }
futures-io   = { git = "https://github.com/Thomasdezeeuw/futures-rs", branch = "write-all-vectored" }
futures-util = { git = "https://github.com/Thomasdezeeuw/futures-rs", branch = "write-all-vectored" }

[dev-dependencies]
http        = { version = "0.2.0", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
mio         = { version = "0.7.0", default-features = false, features = ["os-poll"] }
mio-pipe    = { version = "0.1.1", default-features = false }
serde_test  = { version = "1.0.110", default-features = false }

[profile.release]
opt-level        = 3
debug            = false
debug-assertions = false
overflow-checks  = false
lto              = "fat"
panic            = "abort"
incremental      = false
codegen-units    = 1
rpath            = false

[[bin]]
name = "store"
path = "src/bin/store.rs"

[[bin]]
name = "retrieve"
path = "src/bin/retrieve.rs"

[[bin]]
name = "remove"
path = "src/bin/remove.rs"

[[bin]]
name = "stored"
path = "src/bin/server.rs"

[[bin]]
name = "validate_store"
path = "src/bin/validate.rs"

[workspace]
members = ["bench/hashmap_hash"]
