[storage]
kind = "disk" # Or `memory`.
# For disk storage the path is required, for memory it's ignored.
path = "stored.db"

# Support for thee Hypertext Transfer Protocol (HTTP) version 1.1 protocol.
[http]
# Address to listen on.
address = "127.0.0.1:5080"

# Support for the Redis Serialization Protocol (RESP) version 2 protocol.
# This has the same structure as the HTTP section, see above.
[resp]
address = "127.0.0.1:5378"
