# Minimal stored configuration. See `config.example.toml` for all configuration
# options and documentation of the options.

[storage]
kind = "memory"

# One of the listeners, either http or resp, must be configured.
[resp]
address = "127.0.0.1:5378"
