[package]
name    = "coeus-common"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
edition = "2018"

[dependencies]
futures-io-preview = "0.3.0-alpha.17"
ring               = "0.16.2"

[dev-dependencies]
futures-util-preview = "0.3.0-alpha.17"
